# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fcfd9e8f1890e7399ed48b6e2811e5ee59868584c5c2af8e17aec51a9402135d5601255e6191183e83d69e55661f703ae5744c504106aa98b6a80ab40b6a37ce

test:
  secret_key_base: 0ec6af8e996b4b7ecf5ca9fa872f7720b9dfc6a5f91a051c910c784573b43cb499ef3cdb71ab12d7f948d723ac9bbb8771eec90680a9f33a96dff46eb1c9118a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
